version: "3.8"

services:
  valheim:
    image: akashisn/valheim
    cap_add:
      - SYS_NICE
    volumes:
      - ./saves:/root/saves
      - /mnt/backup/valheim:/mnt/backup/valheim
    environment:
      TZ: "Asia/Tokyo"
      SERVER_NAME: ${SERVER_NAME}
      WORLD_NAME: ${WORLD_NAME}
      PASSWORD: ${PASSWORD}
    ports:
      - 2456-2458:2456-2458
      - 2456-2458:2456-2458/udp
    restart: always