name: valheim

on:
  push:
    paths:
      - '**'
      - '!**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: akashisn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push - valheim
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          tags: |
            akashisn/valheim
          platforms: linux/amd64
          push: true